### ISSUE TITLE
Newlines are not rendered 

### ISSUE THREAD

**Issue by humble-GOAT** [nostrband/libnostrsite#6]
Hi,

I found one minor issue, newlines are not being rendered. 

For example [my note ](https://nostrudel.ninja/#/u/npub1udhl7j34c5g3m4g4nmq3rjqce9hy3q2vfq02d867t49skqk6we4qpegj90/notes)on nostrudel: 

![image](https://github.com/user-attachments/assets/29450eb5-ab72-4c79-8cfa-a4abceed051e)

This is [how it looks](https://humble-goat.npub.pro/post/note1t03nwsqcqvp42q2fj6v87qjdx6xqc6q8y3ljhetzsz4hyaf5dz9q7ra9jp/) on npub.pro:

![image](https://github.com/user-attachments/assets/f7badbe4-2ba5-4850-bbb2-f5224657ad7d)

**Comment by brugeman** [comment]
Fixed, thanks.

**Comment by humble-GOAT** [comment]
Thanks, it's working now.
